apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-dashboard-deployment
  labels:
    app: devops-dashboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devops-dashboard
  template:
    metadata:
      labels:
        app: devops-dashboard
    spec:
      containers:
        - name: devops-dashboard-container
          image: 766363046630.dkr.ecr.ap-south-1.amazonaws.com/devops-dashboard:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: devops-dashboard-service
spec:
  type: LoadBalancer
  selector:
    app: devops-dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
