apiVersion: v1
kind: Service
metadata:
  name: devops-dashboard-service
spec:
  type: LoadBalancer   # creates AWS ELB
  selector:
    app: devops-dashboard   # must match labels in your Deployment
  ports:
    - port: 80              # external port
      targetPort: 5000      # container port inside pod
